export {default as Home} from './Home'
export {default as About} from './About'
export {default as Skills} from './SKills'
export {default as Projects} from './Projects'
export {default as Contact} from './Contact'